package FilterApp;


/**
* FilterApp/FilterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/FilterApp.idl
* martes 27 de abril de 2021 16H33' CEST
*/

public interface FilterOperations 
{
  String getFilterImage (String path);
  void shutdown ();
} // interface FilterOperations
