package FilterApp;


/**
* FilterApp/FilterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/FilterApp.idl
* miércoles 28 de abril de 2021 18H59' CEST
*/

public interface FilterOperations 
{
  String getFilterImage (String path, int filter);
  void shutdown ();
} // interface FilterOperations
